// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAf0tm_cPA-3fXiCMYfYG024xwhXXC3rtA',
    appId: '1:709176652790:web:27a9766a16a50906328dd7',
    messagingSenderId: '709176652790',
    projectId: 'daftar-belanja-9c166',
    authDomain: 'daftar-belanja-9c166.firebaseapp.com',
    databaseURL: 'https://daftar-belanja-9c166-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'daftar-belanja-9c166.firebasestorage.app',
    measurementId: 'G-7PGWB5ECM0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB9427-qxzqyynmZkrutUquS-KcmOJg67Q',
    appId: '1:709176652790:android:04cc37f5a18969ae328dd7',
    messagingSenderId: '709176652790',
    projectId: 'daftar-belanja-9c166',
    databaseURL: 'https://daftar-belanja-9c166-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'daftar-belanja-9c166.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAkQrGUORGCXpnk9jrTU8l5qvMH3g-ogSI',
    appId: '1:709176652790:ios:b6c42888db2d068c328dd7',
    messagingSenderId: '709176652790',
    projectId: 'daftar-belanja-9c166',
    databaseURL: 'https://daftar-belanja-9c166-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'daftar-belanja-9c166.firebasestorage.app',
    iosBundleId: 'com.example.daftarBelanja',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAkQrGUORGCXpnk9jrTU8l5qvMH3g-ogSI',
    appId: '1:709176652790:ios:b6c42888db2d068c328dd7',
    messagingSenderId: '709176652790',
    projectId: 'daftar-belanja-9c166',
    databaseURL: 'https://daftar-belanja-9c166-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'daftar-belanja-9c166.firebasestorage.app',
    iosBundleId: 'com.example.daftarBelanja',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAf0tm_cPA-3fXiCMYfYG024xwhXXC3rtA',
    appId: '1:709176652790:web:1884874338f03e3d328dd7',
    messagingSenderId: '709176652790',
    projectId: 'daftar-belanja-9c166',
    authDomain: 'daftar-belanja-9c166.firebaseapp.com',
    databaseURL: 'https://daftar-belanja-9c166-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'daftar-belanja-9c166.firebasestorage.app',
    measurementId: 'G-46DTTVKPTV',
  );

}